import assert from "node:assert";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { describe, it } from "node:test";
import { spawn, spawnSync } from "node:child_process";
import { berlinDate, receiptBlocksRetry } from "./self-email-once.mjs";
const SCRIPT=new URL("./self-email-once.mjs",import.meta.url).pathname;
function setup(mode="success") { const tmp=fs.mkdtempSync(path.join(os.tmpdir(),"self-email-")),home=path.join(tmp,"home"),html=path.join(tmp,"brief.html"),state=path.join(tmp,"gog.json"),gog=path.join(tmp,"gog");fs.mkdirSync(home);fs.writeFileSync(html,"<p>secret body must not enter receipts</p>");fs.writeFileSync(state,JSON.stringify({sent:[],count:0}));fs.writeFileSync(gog,`#!/usr/bin/env node
const fs=require('fs'),f=process.env.FAKE_STATE,m=process.env.FAKE_MODE,s=JSON.parse(fs.readFileSync(f)),a=process.argv.slice(2),subject=a[a.indexOf('--subject')+1];
if(a[1]==='search'){console.log(JSON.stringify({messages:s.sent.map(x=>({id:x.id}))}));process.exit()}
if(a[1]==='get'){const x=s.sent.find(x=>x.id===a[2]);if(!x||m==='verify-fail')process.exit(1);console.log(JSON.stringify({internalDate:Date.now(),payload:{headers:[{name:'From',value:'iurysza@gmail.com'},{name:'To',value:'iurysza@gmail.com'},{name:'Subject',value:x.subject}]}}));process.exit()}
if(a[1]==='send'){s.count++;if(m==='slow')Atomics.wait(new Int32Array(new SharedArrayBuffer(4)),0,0,300);if(m!=='fail-no-sent'){s.sent.push({id:'m'+s.count,subject});}fs.writeFileSync(f,JSON.stringify(s));if(m==='fail-no-sent'||m==='lost-response')process.exit(1);console.log(JSON.stringify({messageId:'m'+s.count}));process.exit()}
process.exit(2);`);fs.chmodSync(gog,0o755);const date=berlinDate(),subject=`Daily brief ${date}`,args=["--account","iurysza@gmail.com","--date",date,"--subject",subject,"--html-file",html],env={...process.env,HOME:home,CLOCKWORK_HOME:path.join(home,'.local/state/clockwork'),GOG_BIN:gog,FAKE_STATE:state,FAKE_MODE:mode};const run=()=>spawnSync(process.execPath,[SCRIPT,...args],{env,encoding:'utf8'});return{tmp,home,html,state,gog,date,subject,args,env,run}; }
function receipt(x){return JSON.parse(fs.readFileSync(path.join(x.home,'.local/state/clockwork/delivery-receipts/daily-brief-personal',`${x.date}.json`),'utf8'));}
describe("self email once",()=>{
 it("delivers once and redacts body and raw payload",()=>{const x=setup();let r=x.run();assert.strictEqual(r.status,0,r.stderr);assert.strictEqual(JSON.parse(r.stdout).status,'delivered');r=x.run();assert.strictEqual(r.status,0,r.stderr);assert.strictEqual(JSON.parse(r.stdout).status,'already-delivered');assert.strictEqual(JSON.parse(fs.readFileSync(x.state)).count,1);const text=JSON.stringify(receipt(x));assert.doesNotMatch(text,/secret body|payload|OAuth|Bearer/);fs.rmSync(x.tmp,{recursive:true,force:true});});
 it("reconciles a lost send response without retry",()=>{const x=setup('lost-response');const r=x.run();assert.strictEqual(r.status,0,r.stderr);assert.strictEqual(receipt(x).status,'delivered');assert.strictEqual(JSON.parse(fs.readFileSync(x.state)).count,1);fs.rmSync(x.tmp,{recursive:true,force:true});});
 it("fails closed after ambiguous failure and stale attempt",()=>{const x=setup('fail-no-sent');let r=x.run();assert.notStrictEqual(r.status,0);assert.strictEqual(receipt(x).status,'ambiguous');r=x.run();assert.notStrictEqual(r.status,0);assert.match(r.stderr,/retry blocked/);assert.strictEqual(JSON.parse(fs.readFileSync(x.state)).count,1);assert.ok(receiptBlocksRetry({status:'attempting'}));fs.rmSync(x.tmp,{recursive:true,force:true});});
 it("blocks duplicate matching Sent messages",()=>{const x=setup();fs.writeFileSync(x.state,JSON.stringify({sent:[{id:'a',subject:x.subject},{id:'b',subject:x.subject}],count:0}));const r=x.run();assert.notStrictEqual(r.status,0);assert.strictEqual(receipt(x).status,'ambiguous');fs.rmSync(x.tmp,{recursive:true,force:true});});
 it("serializes concurrent callers",async()=>{const x=setup('slow');const call=()=>new Promise(resolve=>{const p=spawn(process.execPath,[SCRIPT,...x.args],{env:x.env});let out='',err='';p.stdout.on('data',d=>out+=d);p.stderr.on('data',d=>err+=d);p.on('exit',code=>resolve({code,out,err}));});const [a,b]=await Promise.all([call(),call()]);assert.strictEqual([a.code,b.code].filter(c=>c===0).length,1);assert.strictEqual(JSON.parse(fs.readFileSync(x.state)).count,1);fs.rmSync(x.tmp,{recursive:true,force:true});});
 it("rejects any other account and unknown arguments",()=>{const x=setup();const args=[...x.args];args[args.indexOf('iurysza@gmail.com')]='other@example.com';let r=spawnSync(process.execPath,[SCRIPT,...args],{env:x.env,encoding:'utf8'});assert.notStrictEqual(r.status,0);r=spawnSync(process.execPath,[SCRIPT,...x.args,'--cc','x@example.com'],{env:x.env,encoding:'utf8'});assert.notStrictEqual(r.status,0);fs.rmSync(x.tmp,{recursive:true,force:true});});
 it("executes when invoked through an installed symlink",()=>{const x=setup();const installed=path.join(x.tmp,"clockwork-self-email-once");fs.symlinkSync(SCRIPT,installed);const r=spawnSync(installed,x.args,{env:x.env,encoding:"utf8"});assert.strictEqual(r.status,0,r.stderr);assert.strictEqual(JSON.parse(r.stdout).status,"delivered");fs.rmSync(x.tmp,{recursive:true,force:true});});
});
